version: "3"

services:
  data:
    build:
      context: "./data"
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: username
      POSTGRES_DB: database

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  ai-bot:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
