version: "3"

services:
  data:
    build:
      context: "./data"
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  client:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_HOST: data
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
